evropa2: "https://ice.actve.net/fm-evropa2-128"
impuls: "http://icecast1.play.cz/impuls128.mp3"
frekvence1: "https://ice.actve.net/fm-frekvence1-128"
rock: "http://icecast6.play.cz/casrock128.mp3"
city: "http://ice.abradio.cz:8000/cityfm128.mp3"